/*
 * Requisition
 * Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.APIEmployeeLookup;
import com.konfigthis.client.model.APIReviewCycleLookup;
import com.konfigthis.client.model.APIReviewGroupLookup;
import com.konfigthis.client.model.APIReviewRating;
import com.konfigthis.client.model.ReviewStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for APIEmployeeReview
 */
public class APIEmployeeReviewTest {
    private final APIEmployeeReview model = new APIEmployeeReview();

    /**
     * Model tests for APIEmployeeReview
     */
    @Test
    public void testAPIEmployeeReview() {
        // TODO: test APIEmployeeReview
    }

    /**
     * Test the property 'summary'
     */
    @Test
    public void summaryTest() {
        // TODO: test summary
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'employee'
     */
    @Test
    public void employeeTest() {
        // TODO: test employee
    }

    /**
     * Test the property 'reviewGroup'
     */
    @Test
    public void reviewGroupTest() {
        // TODO: test reviewGroup
    }

    /**
     * Test the property 'reviewCycle'
     */
    @Test
    public void reviewCycleTest() {
        // TODO: test reviewCycle
    }

    /**
     * Test the property 'ratings'
     */
    @Test
    public void ratingsTest() {
        // TODO: test ratings
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
