/*
 * Requisition
 * Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AccountStatus;
import com.konfigthis.client.model.Address;
import com.konfigthis.client.model.BloodGroup;
import com.konfigthis.client.model.ContingentType;
import com.konfigthis.client.model.CustomField;
import com.konfigthis.client.model.Education;
import com.konfigthis.client.model.EmployeeLookup;
import com.konfigthis.client.model.EmploymentStatus;
import com.konfigthis.client.model.ExitStatus;
import com.konfigthis.client.model.ExitType;
import com.konfigthis.client.model.Experience;
import com.konfigthis.client.model.Gender;
import com.konfigthis.client.model.GroupLookup;
import com.konfigthis.client.model.Image;
import com.konfigthis.client.model.InvitationStatus;
import com.konfigthis.client.model.LookupInfo;
import com.konfigthis.client.model.MaritalStatus;
import com.konfigthis.client.model.Relation;
import com.konfigthis.client.model.TimeType;
import com.konfigthis.client.model.WorkerType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeProfile
 */
public class EmployeeProfileTest {
    private final EmployeeProfile model = new EmployeeProfile();

    /**
     * Model tests for EmployeeProfile
     */
    @Test
    public void testEmployeeProfile() {
        // TODO: test EmployeeProfile
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'countryCode'
     */
    @Test
    public void countryCodeTest() {
        // TODO: test countryCode
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'secondaryJobTitle'
     */
    @Test
    public void secondaryJobTitleTest() {
        // TODO: test secondaryJobTitle
    }

    /**
     * Test the property 'reportsTo'
     */
    @Test
    public void reportsToTest() {
        // TODO: test reportsTo
    }

    /**
     * Test the property 'l2Manager'
     */
    @Test
    public void l2ManagerTest() {
        // TODO: test l2Manager
    }

    /**
     * Test the property 'dottedLineManager'
     */
    @Test
    public void dottedLineManagerTest() {
        // TODO: test dottedLineManager
    }

    /**
     * Test the property 'contingentType'
     */
    @Test
    public void contingentTypeTest() {
        // TODO: test contingentType
    }

    /**
     * Test the property 'timeType'
     */
    @Test
    public void timeTypeTest() {
        // TODO: test timeType
    }

    /**
     * Test the property 'workerType'
     */
    @Test
    public void workerTypeTest() {
        // TODO: test workerType
    }

    /**
     * Test the property 'isPrivate'
     */
    @Test
    public void isPrivateTest() {
        // TODO: test isPrivate
    }

    /**
     * Test the property 'isProfileComplete'
     */
    @Test
    public void isProfileCompleteTest() {
        // TODO: test isProfileComplete
    }

    /**
     * Test the property 'maritalStatus'
     */
    @Test
    public void maritalStatusTest() {
        // TODO: test maritalStatus
    }

    /**
     * Test the property 'marriageDate'
     */
    @Test
    public void marriageDateTest() {
        // TODO: test marriageDate
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'joiningDate'
     */
    @Test
    public void joiningDateTest() {
        // TODO: test joiningDate
    }

    /**
     * Test the property 'professionalSummary'
     */
    @Test
    public void professionalSummaryTest() {
        // TODO: test professionalSummary
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'resignationSubmittedDate'
     */
    @Test
    public void resignationSubmittedDateTest() {
        // TODO: test resignationSubmittedDate
    }

    /**
     * Test the property 'exitDate'
     */
    @Test
    public void exitDateTest() {
        // TODO: test exitDate
    }

    /**
     * Test the property 'employmentStatus'
     */
    @Test
    public void employmentStatusTest() {
        // TODO: test employmentStatus
    }

    /**
     * Test the property 'accountStatus'
     */
    @Test
    public void accountStatusTest() {
        // TODO: test accountStatus
    }

    /**
     * Test the property 'invitationStatus'
     */
    @Test
    public void invitationStatusTest() {
        // TODO: test invitationStatus
    }

    /**
     * Test the property 'exitStatus'
     */
    @Test
    public void exitStatusTest() {
        // TODO: test exitStatus
    }

    /**
     * Test the property 'exitType'
     */
    @Test
    public void exitTypeTest() {
        // TODO: test exitType
    }

    /**
     * Test the property 'exitReason'
     */
    @Test
    public void exitReasonTest() {
        // TODO: test exitReason
    }

    /**
     * Test the property 'personalEmail'
     */
    @Test
    public void personalEmailTest() {
        // TODO: test personalEmail
    }

    /**
     * Test the property 'workPhone'
     */
    @Test
    public void workPhoneTest() {
        // TODO: test workPhone
    }

    /**
     * Test the property 'homePhone'
     */
    @Test
    public void homePhoneTest() {
        // TODO: test homePhone
    }

    /**
     * Test the property 'mobilePhone'
     */
    @Test
    public void mobilePhoneTest() {
        // TODO: test mobilePhone
    }

    /**
     * Test the property 'bloodGroup'
     */
    @Test
    public void bloodGroupTest() {
        // TODO: test bloodGroup
    }

    /**
     * Test the property 'attendanceNumber'
     */
    @Test
    public void attendanceNumberTest() {
        // TODO: test attendanceNumber
    }

    /**
     * Test the property 'probationEndDate'
     */
    @Test
    public void probationEndDateTest() {
        // TODO: test probationEndDate
    }

    /**
     * Test the property 'currentAddress'
     */
    @Test
    public void currentAddressTest() {
        // TODO: test currentAddress
    }

    /**
     * Test the property 'permanentAddress'
     */
    @Test
    public void permanentAddressTest() {
        // TODO: test permanentAddress
    }

    /**
     * Test the property 'relations'
     */
    @Test
    public void relationsTest() {
        // TODO: test relations
    }

    /**
     * Test the property 'educationDetails'
     */
    @Test
    public void educationDetailsTest() {
        // TODO: test educationDetails
    }

    /**
     * Test the property 'experienceDetails'
     */
    @Test
    public void experienceDetailsTest() {
        // TODO: test experienceDetails
    }

    /**
     * Test the property 'customFields'
     */
    @Test
    public void customFieldsTest() {
        // TODO: test customFields
    }

    /**
     * Test the property 'groups'
     */
    @Test
    public void groupsTest() {
        // TODO: test groups
    }

    /**
     * Test the property 'leavePlanInfo'
     */
    @Test
    public void leavePlanInfoTest() {
        // TODO: test leavePlanInfo
    }

    /**
     * Test the property 'bandInfo'
     */
    @Test
    public void bandInfoTest() {
        // TODO: test bandInfo
    }

    /**
     * Test the property 'payGradeInfo'
     */
    @Test
    public void payGradeInfoTest() {
        // TODO: test payGradeInfo
    }

    /**
     * Test the property 'shiftPolicyInfo'
     */
    @Test
    public void shiftPolicyInfoTest() {
        // TODO: test shiftPolicyInfo
    }

    /**
     * Test the property 'weeklyOffPolicyInfo'
     */
    @Test
    public void weeklyOffPolicyInfoTest() {
        // TODO: test weeklyOffPolicyInfo
    }

    /**
     * Test the property 'captureSchemeInfo'
     */
    @Test
    public void captureSchemeInfoTest() {
        // TODO: test captureSchemeInfo
    }

    /**
     * Test the property 'trackingPolicyInfo'
     */
    @Test
    public void trackingPolicyInfoTest() {
        // TODO: test trackingPolicyInfo
    }

    /**
     * Test the property 'expensePolicyInfo'
     */
    @Test
    public void expensePolicyInfoTest() {
        // TODO: test expensePolicyInfo
    }

    /**
     * Test the property 'overtimePolicyInfo'
     */
    @Test
    public void overtimePolicyInfoTest() {
        // TODO: test overtimePolicyInfo
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    public void identifierTest() {
        // TODO: test identifier
    }

}
