/*
 * Requisition
 * Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FieldItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeField
 */
public class EmployeeFieldTest {
    private final EmployeeField model = new EmployeeField();

    /**
     * Model tests for EmployeeField
     */
    @Test
    public void testEmployeeField() {
        // TODO: test EmployeeField
    }

    /**
     * Test the property 'profileFields'
     */
    @Test
    public void profileFieldsTest() {
        // TODO: test profileFields
    }

    /**
     * Test the property 'jobFields'
     */
    @Test
    public void jobFieldsTest() {
        // TODO: test jobFields
    }

}
