/*
 * Requisition
 * Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeaveBalanceListItem
 */
public class LeaveBalanceListItemTest {
    private final LeaveBalanceListItem model = new LeaveBalanceListItem();

    /**
     * Model tests for LeaveBalanceListItem
     */
    @Test
    public void testLeaveBalanceListItem() {
        // TODO: test LeaveBalanceListItem
    }

    /**
     * Test the property 'leaveTypeId'
     */
    @Test
    public void leaveTypeIdTest() {
        // TODO: test leaveTypeId
    }

    /**
     * Test the property 'leaveTypeName'
     */
    @Test
    public void leaveTypeNameTest() {
        // TODO: test leaveTypeName
    }

    /**
     * Test the property 'accruedAmount'
     */
    @Test
    public void accruedAmountTest() {
        // TODO: test accruedAmount
    }

    /**
     * Test the property 'consumedAmount'
     */
    @Test
    public void consumedAmountTest() {
        // TODO: test consumedAmount
    }

    /**
     * Test the property 'availableBalance'
     */
    @Test
    public void availableBalanceTest() {
        // TODO: test availableBalance
    }

    /**
     * Test the property 'annualQuota'
     */
    @Test
    public void annualQuotaTest() {
        // TODO: test annualQuota
    }

}
