/*
 * Requisition
 * Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FilteringOptions;
import com.konfigthis.client.model.PagingOptions;
import com.konfigthis.client.model.SortingOptions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for QueryOptions
 */
public class QueryOptionsTest {
    private final QueryOptions model = new QueryOptions();

    /**
     * Model tests for QueryOptions
     */
    @Test
    public void testQueryOptions() {
        // TODO: test QueryOptions
    }

    /**
     * Test the property 'pagingOptions'
     */
    @Test
    public void pagingOptionsTest() {
        // TODO: test pagingOptions
    }

    /**
     * Test the property 'sortingOptions'
     */
    @Test
    public void sortingOptionsTest() {
        // TODO: test sortingOptions
    }

    /**
     * Test the property 'filterOptions'
     */
    @Test
    public void filterOptionsTest() {
        // TODO: test filterOptions
    }

    /**
     * Test the property 'searchableOptions'
     */
    @Test
    public void searchableOptionsTest() {
        // TODO: test searchableOptions
    }

    /**
     * Test the property 'fieldsToReturn'
     */
    @Test
    public void fieldsToReturnTest() {
        // TODO: test fieldsToReturn
    }

}
