/*
 * Requisition
 * Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ScorecardSectionDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ScoreCardDTO
 */
public class ScoreCardDTOTest {
    private final ScoreCardDTO model = new ScoreCardDTO();

    /**
     * Model tests for ScoreCardDTO
     */
    @Test
    public void testScoreCardDTO() {
        // TODO: test ScoreCardDTO
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'jobId'
     */
    @Test
    public void jobIdTest() {
        // TODO: test jobId
    }

    /**
     * Test the property 'candidateId'
     */
    @Test
    public void candidateIdTest() {
        // TODO: test candidateId
    }

    /**
     * Test the property 'stageId'
     */
    @Test
    public void stageIdTest() {
        // TODO: test stageId
    }

    /**
     * Test the property 'interviewId'
     */
    @Test
    public void interviewIdTest() {
        // TODO: test interviewId
    }

    /**
     * Test the property 'overallFeedbackDecision'
     */
    @Test
    public void overallFeedbackDecisionTest() {
        // TODO: test overallFeedbackDecision
    }

    /**
     * Test the property 'overallComments'
     */
    @Test
    public void overallCommentsTest() {
        // TODO: test overallComments
    }

    /**
     * Test the property 'feedbackSubmittedByName'
     */
    @Test
    public void feedbackSubmittedByNameTest() {
        // TODO: test feedbackSubmittedByName
    }

    /**
     * Test the property 'sections'
     */
    @Test
    public void sectionsTest() {
        // TODO: test sections
    }

}
