/*
 * Requisition
 * Here's our story,  It all began with the frustration of using software that sucks. Prior to starting Keka, our core team was a 100 person business that needed an easy to use software for managing employees. We looked everywhere and all we found were software that was lousy and hard to use. We felt SME businesses in India deserved something better. Something awesome actually!  Thus emerged Keka!
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AttendanceSummaryPagedResponse;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AttendanceApi
 */
@Disabled
public class AttendanceApiTest {

    private static AttendanceApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AttendanceApi(apiClient);
    }

    /**
     * Get all Attendance Records
     *
     * Gets all Attendance records between date range &#x60;from&#x60; and &#x60;to&#x60;.If both &#x60;from&#x60; and &#x60;to&#x60; are not specified, last 30 days records are returned.From &#x60;date&#x60; should be before &#x60;to&#x60; date.The difference between &#x60;from&#x60; and &#x60;to&#x60; date cannot be more than **90** days.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecordsInRangeTest() throws ApiException {
        String employeeIds = null;
        OffsetDateTime from = null;
        OffsetDateTime to = null;
        Integer pageNumber = null;
        Integer pageSize = null;
        AttendanceSummaryPagedResponse response = api.getRecordsInRange()
                .employeeIds(employeeIds)
                .from(from)
                .to(to)
                .pageNumber(pageNumber)
                .pageSize(pageSize)
                .execute();
        // TODO: test validations
    }

}
